# Site settings
title: Solace Samples C
baseurl: "/solace-samples-c" # the subpath of your site, e.g. /solace-samples-java
repository: https://github.com/SolaceSamples/solace-samples-c

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
links-downloads: http://dev.solace.com/downloads/
links-community: http://dev.solace.com/community/
docs-vmr-setup: http://docs.solace.com/Solace-VMR-Set-Up/Setting-Up-VMRs.htm
docs-core-concepts: http://docs.solace.com/Features/Core-Concepts.htm
docs-api-ref: http://docs.solace.com/API-Developer-Online-Ref-Documentation/c/index.html

#----------------------------------------------------
# Generally don't modify items below this point
url: "solacesamples.github.io" # the base hostname & protocol for your site

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  tutorials:
    output: true
    permalink: /:path/
